name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Set environment variable
        run: echo "SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Grant execute permissions
        run: chmod +x -R ./.github/scripts/

      - name: Unit tests
        run: ./.github/scripts/run_unit_tests.sh

      - name: Functional test - categorisation - tuning
        run: ./.github/scripts/run_categorisation_tuning.sh

      - name: Functional test - categorisation - no tuning
        run: ./.github/scripts/run_categorisation_no_tuning.sh

      - name: Functional test - regression - tuning
        run: ./.github/scripts/run_regression_tuning.sh

      - name: Functional test - regression - no tuning
        run: ./.github/scripts/run_regression_no_tuning.sh